### ISSUE TITLE
Related to your rails issue

### ISSUE THREAD

**Issue by nathanvda** [alexeymuranov/raclette#2]
Hi there,

your rails issue https://github.com/rails/rails/issues/7236 got me a bit baffled, as to why you would do anything like that. So I took a look at your code, and as far as i can tell, inside your `EventsController` you need to define your classes again because you want to be able to define some constants on class level, but which could change per controller. 

Because you inherit from the original model, you also have to redefine all your relations you want to use.

I hope you _feel_ your current solution is going wrong, against the framework. It is not simple, it is not clean, it is frankly awful.

Why do not something simple, like:

```
class EventsController < SecretaryController
  CONFIG = { :event => { :all_sorting_columns => [ :title, :event_type, :date, :start_time,  :supervisors ],
                                            :default_sorting_column => :date},
                        :weekly_event => { :all_sorting_columns => [ :title, :event_type, :lesson, :week_day, .... <snip> ],
                                                           :default_sorting_column => :end_on
                         :person => { :all_sorting_columns => [ :ordered_full_name,  :email ],
                                                :default_sorting_column => :ordered_full_name }
                         :member => { :all_sorting_columns => [ :ordered_full_name, :email, :account_deactivated, :tickets_count ],
                                                  :default_sorting_column => :ordered_full_name }
```

and use that instead? 

As I understand it, you are trying, per controller, to store some configuration how everything should be shown. 
My suggestion expresses your intent much more clearly that what you are now trying to do now (in my personal opinion).

If you do it like I propose, it not only becomes much clearer, but it also would not be a big change to load this configuration from yaml or some user-configuration instead.

Hope this helps.

**Comment by alexeymuranov** [comment]
@nathanvda, thanks for the idea, i will think about it.  I wanted to report the rails issue regardless whether i will find a workaround, because i think the behavior was weird, and could indicate some hidden problems in AR.  I see no reason why it shouldn't be possible to duplicate an AR class like any other object.

**Comment by alexeymuranov** [comment]
@nathanvda, it would be not enough to store configuration somewhere, i would also need to make the model class methods, like `filter` and `sort`, use the configuration.  Given the rules for constant lookup in Ruby, i do not see an easy way.

**Comment by nathanvda** [comment]
Hi Alex, i do not quite understand your problem. You can easily define a `filter` and `sort` which need a parameter, which is the configuration. Or you use a presenter/decorator class, or a helper function which does that for you.

Afaik you are only configuring which fields to select, which fields could be filtered on, and which fields need to be sorted, I do not see why this should be in your model. This is pure configuration, presentation/view code.

Also, depending on what you are trying to do (you seem to be building generic forms/index views), maybe https://github.com/leikind/wice_grid is something to consider?

Hope this helps,

Nathan

**Comment by alexeymuranov** [comment]
Nathan, in my opinion these configuration options are not different from `default_scope`, so i do not see why they cannot be in a model.  Of course one may say that `default_scope` is a bad habit too.  Default sorting can be seen as presentation or as a model behavior.  My problem is that i do not want this behavior to be the same in all parts of the application, and i thought to use inheritance for this. Maybe passing an extra parameter would work, but for me it was more readable this way. Thanks for the link in any case, i will think about it and about Draper.

**Comment by nathanvda** [comment]
> "...more readable this way"

We agree to disagree :)
